map $request_method $limit_key {
    default "";
    POST    $binary_remote_addr;
}

limit_req_zone $limit_key zone=timeline_limit:10m rate=1r/m;

server {
    listen 80;
    server_name rmacasa.duckdns.org;

    if ($host = rmacasa.duckdns.org) {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name rmacasa.duckdns.org;

    location /api/timeline_post {
        proxy_pass http://myportfolio:5000/api/timeline_post;
        limit_req zone=timeline_limit;
        limit_req_status 429;
    }

    location / {
        proxy_pass http://myportfolio:5000/;
    }

    ssl_certificate /etc/letsencrypt/live/myportfolio/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/myportfolio/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/myportfolio/chain.pem;
}